(function(window){
	var lang = {
            loading: "加载中",
            newCategory: "新建分类",
            title: "在线考试系统",
            confirmSubmit: "确认交卷",
            exitTestConfirm: "亲，您确定要离开这个页面吗？{n}{n}离开这个页面将会使您的考试成绩为0, {n}{n}如果您想切换试题，您可以点击上一页下一页按钮在页面间切换.",
            guideline:"提示",
            needAnswerEveryQuestion:"您需要继续回答每一个问题并完成考试",
            ok:"好的",
            sure: "确定",
            needAnswerAll:"需要回答所有试题",
            continueAnswerQuestion:"继续答题",
            dontAnswerAndSubmit:"不想答了， 交卷",
            answerAllQuestionsTip: "亲，<strong>您还有{0}题未答</strong>, 请答完所有题",
            confirmSubmitTip:"您确认现在交卷吗？",
            confirmSubmitTipWithTime:"您确认现在交卷吗？离考试结束还有{0}分钟，您不检查一下吗？",
            submiting:"提交中， 请不要刷新页面",
            haveACheck:"再检查一下",
            dontAllowChangeAnswerTip:"试卷不允许返回修改答案，您需要答完本页所有题",
            needFillAllTheInformation: "您需要填写所有数据正确后方可进行考试，请检查是否有数据没输入，是否有数据格式不正确，例如，手机格式，邮件格式是否正确",
            ajaxTable: {
                loading: "加载中",
                all: "全部",
                requestError: "无法完成数据加载请求， 请重新刷新该界面, 如果刷新后，问题还在， 请检查网络链接是否正常",
                pageSizeSelect: "<span class='seperator'>|</span>显示 _MENU_ 记录",
                totalRecords: "<span class='seperator'>|</span>共有 _TOTAL_ 条数据记录",
                noRecords: "没有数据记录",
                noData: "表中无数据",
                noMatchRecord: "没有找到相关数据",
                prev: "上页",
                next: "下页",
                last: "尾页",
                first: "首页",
                page: "页"
            },

            charts: {
                wrongRightsDistribute: "试题答对答错数分布",
                didRights: "做对",
                didWrongs: "做错"
            },

            examQuestions: {

                removeQuestionFailed: "从试卷中移除试题失败.",
                removeQuestion: "移除",
                uncategoried: "默认分类",
                removedQuestionFromExam: "试题已从试卷中移除",
                questionAddedToExam: "试题已添加到试卷",
                specifyQuestionCount: "试题个数请不要小于0或要为数字",
                selectingQuestionsNow: "在题库选择试题中...",
                selectedNoQuestions: "没有选中任何试题，请先加一些试题到试题库中",
                select: "选择",

                ramdomSelectBeforeExam: "随机试题<i>每个考生的题都不一样</i>",
                preSelectQuestions: "固定试题<i>所有考生试题都相同</i>",

                rePloginlease: "请重新登录后操作",
                dragToReorder: "拖动以改变试题显示顺序",
                changeAdditionFailed: "修改试题数据操作失败，有可能您没有登录，请重新登录后再试",
                setAddition: "设为附加题",
                cancelAddition: "取消附加题",
                additionQuestion: "附加题",
                preSelectQuestionFromCategories: "将从题库中选择{0}个试题",

                saveSuccess: "保存成功， 即将跳转...",
                saveFailed: "保存失败，请重新登录后再试",
                changeScore: "修改分数",
                removeQuestionsAndChange: "切换部分后，将移除该试卷的所有试题。",
                switchStandardMode: "切换标准模式",
                moveAndChange: "移除试题并切换",
                moveThenChange: "请保留一个部分后切换至标准模式",
                sectionN: "第{0}部分",
            },
            notice: "温馨提示",
            error: "错误",
            finishedPercent: "已完成{0}%",
            exportFailed: "导出考试记录失败，请联系我们客服QQ: 3322628959",
            exportSuccess: "<span class='success'>导出考试记录成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/><span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportCollectionSuccess: "<span class='success'>导出考试收集项成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/><span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            _delete: "删除",
            cancel: "取消",
            sureToDeleteQuestions: "您确定要删除已选择的试题吗？",
            deleteSuccessfully: "删除成功",
            withoutDeletePermission: "您当前无权删除试卷",
            moveQuestionToCategoryFailed:"移动试题到分类失败，请稍后重试",
            deleteQuestionsFailed:"删除试题失败，请稍后重试",
            moveQuestionToCategorySuccess:"移动试题到分类成功",
            pleaseSelectFirst:"请先选择一项",
            noRecordMatched:"<div class='add-questions-box-no-questions-tips text-center' style='position:absolute;top:40%;left:50%;margin-left:-160px;color:#999;'>当前未搜索出符合条件的试题，请重新筛选<br>附注: 已被添加到试卷的试题不会再显示，以防止试题被重复添加！</div>",
            resubmit:"重新交卷",
            noNetworkTip:"当前无法链接到优考试服务器， 请检查您的网络链接，然后再点重新交卷按钮",
            haveSubmitError:"当前无法链接到网络，请检查网络链接，然后重试",
            copiedToClipboard:"已复制到剪贴板",
            retry:"重试",
            sureDeleteExam:"<div>您确定要删除{0}个选择的试卷吗？删除后，该试卷的考试记录，统计分析将一起被删除。</div><div class='delete-exam-math'>计算结果：{1}+{2}=<input name='sum'></div>",
            score:"得分",
            count:"次数",
            nStudentGotNScore:"<b>{point.y}</b> 个考生得分 <b>{point.category}</b>",
            yes:"是",
            no:"否",
            deleteFailed:"删除失败，请重新登录后在试",
            sendedEmail:"邮件发送成功",
            sendingEmail:"正在发送邮件",
            confirmDeleteField:"确认要删除该信息项吗？",
            modify:"修改",
            modifing:"修改中..",
            deleteCategory:"您确定要删除分类：<strong>{0}</strong> ？",
            add:"增加",
            edit:"编辑",
            adding:"添加中...",
            deleteSelectedCategories:"您确定要删除已选择的分类吗？",
            doexamMiniTakenTimeLimitTip:"本次考试限制{0}分钟后方可交卷，当前已过{1}，请在{2}后再次交卷",
            nminutes:"{0}分钟",
            nseconds:"{0}秒钟",
            nquestions:"%d题",
            selectedncategory:"将从<b> {0} </b>个分类随机抽取<b> {1} </b>个试题.",
            viewqtcountofcate:"点击查看分类里各题型试题数量",
            allCategoryConflictWithOther:"所有分类和其他分类不能同时存在，您确定要添加吗？",
            canceledRequest:"您已取消请求",
            invalidResponce:"无效的返回数据，请检查您是不是过了很久后回来考试，如果是， 请重新开始考试",
            deletedNQuestions:"成功删除{0}个试题",
            needToUpgrad:"升级会员",
            collectionNeedUpgradeDesc:"您当前的会员级别无法添加更多的信息收集项, 请<i>升级更高级别会员</i>。",
            upgradeNow:"现在升级",
            needToBuy:"购买正版",
            needToBuyPrompt:"您的试用期<strong>已过</strong>. 如果想继续使用, 请购买正版。",
            buyNow:"现在购买",
            needUpgradeDesc:"您当前的会员级别不支持该功能, 请点击下面的按钮 <i>升级会员</i>",
            multipleResponseQuestionTip:"第{0}题为多选题，请至少选择2个选项",
            reviewConfirmTip:"<div style='text-align:left'>关于使用【纠错功能】说明:<ul><li>如因试卷中的问答题在判分时给错分数，可进行纠错，若系统判分无异常情况，建议不要再次纠错，避免误操作</li><li>因原试题内容或答案有误导致判分结果出现错误，可联系客服帮您重新判卷</li></ul></div>",
            forceConfirmTip:"我们建议只强制提交完成率为80%以上的试卷， 当前完成率为{0}, 是否继续交卷？",
            takenSubmiting:"强制交卷中，请稍后",
            takenSubmited:"强制提交成功",
            clickToCopy:"点击复制",
            pleaseFirstAnswerNQ:"请先回答<strong>第{0}</strong>题后再交卷",
            field:{
                canNotBeEmpty: "{0}不能为空",
                atLeastNCharacter: "{0}至少写{1}个字符",
                lessThanNCharacter: "{0}请不要超过{1}个字符",
                equalToNCharacter: "{0}请写{1}个字符",
                onlyChinese: "{0}请只填中文",
                onlyAlphabet: "{0}请只填英文字母",
                onlyNumber: "{0}请只填数字",
                invalidCharacter: "{0}有不允许的字符，只支持填写{1}",
                invalidField: "您输入的不是有效的{0}, 请检查"
            },
            gradeInvalidScore:"您判给试题的得分不能超过试题的总分，请返回修改",
            limitedAdminAccountTip:"您只能免费添加{0}个子管理账号，如果需要更多子管理账号，请付费购买",
            featureInTest:"该功能正在紧张的内部测试中，请稍后",
            adminChangedPassword:"修改密码成功",
            adminFailChangePassword:"修改密码失败，错误信息：{0}",
            selectColumnMatch:"请选择第{0}列的数据标签",
            deleteStudenstConfirm:"您确定要删除选择的考生吗？将要删除{0}个考生",
            deletedNStudents:"成功删除 {0} 个考生",
            addedSfidTip:"已添加了{0}, 请不要重复添加",
            newSfidTitle:"新建考生字段",
            savedSuccessfully:"保存成功",
            chgpwdSuccess:"修改密码成功",
            mvStuToGroup:"确定要移动{0}个考生到组{1}",
            mvedNStuToGroup:"成功移动{0}个考生到组{1}",

            addCategory: "添加分类",
            delCategory: "删除分类",
            editCategoryName: "编辑分类名称",
            delCategoryAndDelExam: "选择的分类将被删除，分类中所包含的试卷将会移动至系统默认分类。",
            delExam: "删除试卷",
            moveExamToDefaultCategory: "移动试卷到默认分类",
            delCategoryAndDelQuestion: "选择的分类将被删除，分类中所包含的试题将会移动至系统默认分类。",
            delQuestion: "删除试题",
            moveQuestionToDefaultCategory: "移动试题到默认分类",
            canNotDelCategory: "无法删除该分类！",
            pleaseSelDelCategory: "请选择要删除的分类！",
            pleaseInputCategoryName: "请输入分类名称！",
            addAStudent: "添加考生",
            modifyStudent: "修改考生",
            clickSelUnSelCategory: "点击勾选/取消勾选分类",
            pleaseCheckNeedMoveCategory: "请勾选需要移动的分类！",
            addChildCategory: "添加子分类",
            deleteBothQuestionBank: "删除且从题库中也删除",
            newGroup: "新建分组",
            forceSubmiting: "强制交卷中...",
            forceSubmitingTip: "<span style='color:#f00'>批量交卷中，请不要刷新该页面，否则会导致交卷不成功</span>",
            forceSubmitConfirm: "确认要强制交卷 {0} 个考试吗？",
            forceSubmited: "强制交卷完成，页面数据将重新加载",
            defaultCategory: "默认分类",
            pleaseSelectCategory: "请选择分类",
            rename: "重命名",
            allQuestions: "所有试题",
            allExams: "所有试卷",
            newChildCategory: "新建子分类",
            deleteStudentFieldTip: "你确定要删除字段 <strong>{0}</strong> 吗？删除后所有考生都将没有该信息，且<strong style='color:#f00'>无法恢复！</strong>",
            togetherQuestions: "道试题",
            select: "选择",
            altogether: "共",
            deleteExamsSuccess: "成功删除{0}个试卷",
            deleteNExamsSuccessNFail: "成功删除{0}个试卷, {1}个因为没有权限而删除失败",
            fromfrom: "从",
            fromto: "至",
            week: "星期",
            today: "今天",
            yesterday: "昨天",
            lastWeek: "上周",
            lastMonth: "上月",
            lastNDays: "过去{0}天",
            customize: "自定义",
            monthNames: "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
            daysOfWeek: "周日,周一,周二,周三,周四,周五,周六",
            eachQuestion: "每题",
            point: "分",
            totalScore: "总共<b>%s</b>分.",
            filterByTime: "按时间过虑",
            clearTimeFilter: "不限时间",
            existQuestionsDuplicateTip: "检测到有 {0} 道试题重复, 已为您标出多余的重复试题，请根据具体情况适当删除。",
            totalNScore: "总共{0}分",
            examFieldsNoItemsTip: "请点击框右上角的按钮添加一项",
            enterContentPlease: "请输入内容",
            editSelectFieldTip: "点击添加显示标签",

            pleaseCheckMoveExams: "请先勾选需要移动的试卷。",
            examsMoveCategorySuccess: "试卷移动分类成功。",
            examsMoveCategoryFail: "You currently have no permission to modify the exam",
            canNotExportStuAnswersDesc: "该试卷采用随机抽题模式，暂不支持导出考生答案到Excel！目前仅固定试题试卷支持导出考生答案。",
            hasNoExamrecords: "该试卷暂无考试记录",
            resumeTestAfterBreakTimeInfiniteTip: "您已选择中断后可以在<strong>任何时间</strong>返回继续考试。只有在考生点击交卷后才算完成一次考试",
            pleaseFirstDeleteChild:"请先删除子级后再删除",
            areYouSureToDelete:"您确定要删除 {0} 吗？",
            onlySupportTreeLevelTip:"当前仅支持三个级联菜单，您已经创建三个了",
            dragToSortTip:"拖动可调整顺序",
            SelectGroupByTemplate: "按模板分组导入",
            selectQuestionsImportCategory: "选择试题导入的分类",
            pleaseSelectQuestionsImportCategory: "请选择试题导入的指定分类！",
            defaultCategoryCannotCreateChild: "默认分类无法创建子分类！",
            selectImage:"选择图片",
            changeImage:"更换图片",
            imageSizeNotice:"建议大小:295*413",
            imageTypeIsNotRight:"文件类型不正确",
            imageSizeIsNotRight:"图片最大为1M",
            scoreToScore: "{0}-{1}分",
            removeScoreRange: "移除",
            endMoreThanStart: "结束值应该大于等于开始值",
            valueShouldLargeThanZero: "值必须要大于等于0小于9999",
            filterTipsScore: "成绩: {0}",
            filterTipsGroup: "分组: {0}",
            filterTipsGroupScoreToScore: "分组: {0}-{1}分",
            filterTipsDateTitle: "日期: {0} - {1}",
            filterTipsDate: "{0} - {1}",
            filterTipsDateNotCustom: "日期: {0}",
            filterLabelAndValue: "{0}: {1}",
            doexamInTwoPlaceTip: "系统检查到您的账号正在另一个地方进行考试，本次考试已暂停，如果您希望继续考试，请按原来的方式再次进入。请不要在多个地方进行考试！",
            needToUpgrade:"升级",
            exportQuestionsSuccess: "<span class='success'>导出试题成功</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportStudentsAnswersSuccess: "<span class='success'>导出考生答案成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportCountTooMuch: "单次导出试题的数量不超过150条",
            studentExistConfirmModifyTip: "考生已经存在，不能再重新添加，您需要修改考生的信息吗？",
            allowExportTakenCoutAndUpdateTip: "将要导出{0}条数据，您当前会员级别一次只能导出{1}条记录。<br>如需无限制，请升级到企业会员。",
            exportReportsFileNameSelectorTitle: "自定义考生报告文件名",
            allStudent: "所有考生",
            defaultStudent: "默认分类",
            delGroup: "删除分组",
            newChildGroup: "新建子分组",
            newGroup: "新建分组",
            isCustomFileName:"是否自定义考生报告文件名",
            isCustomFileNameTips:"是否自定义考生报告文件名<br>例如：姓名-邮箱-手机.pdf",
            currentFileName:"当前文件名格式：{0}.pdf",
            deleteMediaFileConfirmPrompt: "您确定要删除媒体文件吗？",
            browserNotSupportAudioPrompt: "您的浏览器不支持音频播放，请升级或更换浏览器。",
            browserNotSupportVideoPrompt: "您的浏览器不支持视频播放，请升级或更换浏览器。",
            uploadFileFailPrompt: "文件上传失败，请重新上传。",
            media: "媒体",
            addQuestionMedia: "添加试题媒体",
            addMedia: "为题干添加音视频文件",
            linkOrFileMimeTypeErr: "链接地址或文件格式错误。",
            uploadErrFileSizeLimitPrompt: "文件大小不能超过%s。",
            mediaFileSupportPrompt: "只支持mp3、mp4格式的媒体文件。",
            filterTipsRanking: "排名: {0}",
            startTimeisempty: "开始时间不能为空",
            endTimeisempty: "结束时间不能为空",
            endTimeIsLessThanStarTime: "结束时间应该大于开始时间",
            default: "默认",
            ungradedPaperTips: "导出的数据包含未批改的试卷，请批改后再导出！",
            deleteGroupTips: "当前选中的分组中共含有{0}个考生，要删除组，请先移动或者删除组里的考生！",
            deleteGroupReTips: "确定要强制删除当前选中的组吗？将会删除{0}个考生，且不可恢复！",
            verifyResultTips: "结果不对请重新计算",
            moveUp: "上移",
            moveDown: "下移",
            newFieldTips1: "不可以重复添加与<strong>{0}</strong>字段相似的字段，请使用系统中已存在的<strong>{0}</strong>字段",
            newFieldTips2: "<strong>{0}</strong>字段已经存在系统中，不可以重复添加",
            newFieldLimit: "您的自定义字段已经达到16个，如需添加更多，请删除一些原有的自定义字段",
            pleaseSelectExamCategory: "请选择试卷分类",
            pleaseSelectQuestionCategory: "请选择试题分类",
            verifyQuestionDeletedTips: "请输入上面的计算结果：",
            noGroup: "未分组",
            selectMultipleTips: "请选择多个组",
            allStuGroups: "所有考生组",
            allGroupsConflictWithOther: "所有考生组和其他考生组不能同时存在，您确定要添加吗？",
            pleaseSelectGroup: "请选择分组",
            ordersCreatedDate: "订单日期",
            wrongAccessUserName: "帐户名有误，请核实后提交",
            supportPersonalAccountOnly: "只支持账户类型为个人的账户",
            wrongAccessNo: "银行卡号有误，请核实后提交",
            informationConfirm: "信息确认",
            userRealNameWithValue: "真实姓名:{0}",
            accessNoWithValue: "银行卡号:{0}",
            accessTypeWithValue: "银行类型:{0}",
            enterYourAmount: "请输入提现金额",
            pleaseSelectYourCard: "请选择银行卡",
            sureDeleteAccess: "是否删除尾号: <strong>{0}</strong> 的 <strong>{1}</strong> 卡。",
            withdrawNotEnoughTips: "当前余额为{0}元，提现金额不能小于100元",
            deductWithdrawalFeesTips: "额外扣除{0}元的服务费(费率10%)",
            notLessThanZeroTips: "必须填写大于0的数字",
            addAccessNo: "添加银行卡",
            betweenSixteenAndNineteen: "银行卡号长度必须在16到19之间",
            emptyAccessNo: "银行卡号为空",
            rechargeSmsTitle: "短信充值",
            startExamTitle: "开始考试",
            startAdvanceTitle: "开始闯关",
            smsAmounts: "{0}元",
            deleteOneExam: "<div>您确定要删除该试卷吗？删除后，该试卷的考试记录，统计分析将一起被删除。</div><div class='delete-exam-math'>计算结果： {0}+{1}=<input name='sum'></div>",
            enterTheCorrectAnswer: "请输入正确答案",
            endtimeShouldMoreThanStarttime: "结束时间应该大于开始时间，请重新设置",
            selectAGroup: "请选择组",
            phoneNumberCanNotBeBlank: "手机号码不能为空",
            smsSendSuccessfully: "短信发送成功",
            smsFailedToSend: "短信发送失败",
            accountCanNotBeEmpty: "账号不能为空",
            phoneNumberIsNotCorrect: "请输入正确的手机号码",
            emailFormatError: "邮箱格式错误",
            notifyTestersAndBeginExam: "通知考生，开始考试",
            notifyTestersToExam: "通知考生考试",
            sureToStopExam: "确定停止考试吗？",
            stopExam: "停止考试",
            restartExam: "重新开始考试",
            allChecked: "全选",
            failToSendEmails: "邮件发送失败",
            resendMessageToStudent: "向 {0} 发送短信",
            smsSendSuccessfullyAndCheckSms: "短信发送成功，是否查看短信记录",
            atLeastAddOneAccount: "请至少添加一个邮件",
            atLeastAddOnePhone: "请至少添加一个手机号码",
            licenseValue: "访问码：{0}",
            examNoQuestionsTip:"试题数量不能为0, 请至少添加一道试题！",
            pleaseEnterCorrectPhoneNumber: "请输入正确的手机号码",
            pleaseEnterCorrectIDNumber: "请输入正确的身份证号码",
            resendSmsWithValue: "重新发送({0})",
            sendVertificationCode: "发送验证码",
            idCardImageIsEmpty: "请选择身份证图片",
            idCardImageSizeIsTooLarge: "身份证图片大于2M",
            pleaseFillYourRealName: "请填写您真实的姓名",
            nameIsEmpty: "姓名不能为空",
            pleaseFillVerificationCode: "请输入验证码",
            nameAuthentication: "实名认证",
            nameAuthenticationTips: "为了保护您的资金安全，您需要进行实名认证才可以使用提现功能。",
            recertification: "重新认证",
            recertificationTips: "实名认证失败，请重新认证",
            exportNoExamSuccess: "<span class='success'>缺考考生名单导出成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportNoExamFailed: "导出全部未考试考生名单失败，请联系我们客服QQ: 3322628959",
            exportRewardsSuccess: "<span class='success'>闯关奖励列表导出成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportRewardsFailed: "导出奖励列表失败，请联系我们客服QQ: 3322628959",
            examNameLengthIsIncorrect: "试卷名称不能超过40个字符。",
            downloadMonitoringPicture: "下载监控图片",
            monitoredPicture: "监控图片",
            download: "下载",
            deletedAndReload: "已删除全部考试中试卷，页面将刷新",
            forceSubmitAllPendingConfirm: "确认要强制交卷所有考试中的考试吗？",
            exportSpecifiedGroup: "是否导出 {0} 组的考生信息",
            exportStudentsSuccessTips: "<span class='success'>导出考生组信息成功</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            failedExportStudentsInfo: "导出考生信息失败，请联系我们客服QQ: 3322628959",
            sureToDeleteAllDoingExams: "<div>是否删除全部考试中记录?</div><div class='delete-exam-math'>计算结果： {0}+{1}=<input name='sum'></div>",
            onlyOneExamCanBeSelectedOnly: "只能选择一张试卷",
            checkingDuplication: "检查重复中...",
            duplicatedNTimes:"COM_EXAMS_DUPLICATED_N_TIMES",
            theNthQuestionAndDuplicatedNum: "第{0}题 重复{1}次",
            pleaseCheckArchivedExams: "请勾选需要归档的试卷",
            archiveExamsSuccessfully: "归档成功",
            archivedExams: "归档试卷",
            whetherToArchiveExams: "确定要归档所选中的{0}份试卷吗？",
            viewArchivedExams: "已归档的试卷可以在归档页面中查看",
            archive: "归档",
            sureToDeleteSelectedFiles: "COM_EXAMS_SURE_TO_DELETE_SELECTED_FILES",
            optionScoreShouldBeGreaterThanZero: "选项自定义分数必须大于0",
            deleteArchivedExamsSuccessfully: "成功删除{0}个归档试卷",
            sureToDeleteSelectedFilesPermanently: "确定要永久删除所选试卷吗？",
            deletePermanently: "永久删除",
            sureUnarchive: "确定还原",
            unarchiveTips: "试卷会被还原到【试卷管理】之前所在的分类",
            sureToDeleteTask:"确定删除该记录吗？",
            sureToDeleteAllTask:"您确定要删除已选中记录吗？",
            pleaseAgree:"未同意协议不能进行提现",
            pleaseReenterIt:"请输入0-{0}范围的分数",
            giveUpTheOperation:"放弃纠错",
            startToCorrectError:"开始纠错",
            alreadyTested: "已考人数: {0}人",
            haveNoPhonesCount: "已<span style='color:#FF962A'>{0}</span>人无手机号码",
            mobileNumbersEnter: "已输入<span style='color:#56baed'>{0}</span>个手机号码",
            makeUpStudentHasPhone: "缺考考生列表中已有手机号的共有<span style='color:#FF962A'>{0}</span>人",
            makeUpStudentHasEmail: "缺考考生列表中已有邮箱的共有<span style='color:#FF962A'>{0}</span>人",
            viewSmsStatus: "查看短信发送状态",
            sendSMSTipsOne: "已经发送{0}条短信，详情请看短信记录",
            sendEmailTipsOne: "成功发送{0}封邮件，详情请看邮件记录",
            sendSMSTipsTwo: "成功发送{0}封邮件，发送失败{1}封，详情请看邮件记录",
            sendEmailTipsTwo: "成功发送{0}条短信，发送失败{1}条，详情请看短信记录",
            emailEnter: "已输入<span style='color:#56baed'>{0}</span>个邮箱",
            waitToSend: "等待发送",
            exportStudentsAnswerTips: "如需导出考生记录，请先强制交卷再完成批卷",
            viewEmails: "查看邮件发送状态",
            resendNMessages: "将重新发送{0}条短信",
            saveAndSend: "保存并发送",
            newRetestGroup: "新建补考组",
            haveNotEmailCount: "已<span style='color:#FF962A'>{0}</span>人无邮箱",
            studentsMissing: "缺考人数: {0}人",
            noSuchOption: "没有该选项",
            stayTuned: "敬请期待",
            movingToGroup: "正移动到补考组...",
            movingToGroupTips: "正移动到补考组，请勿刷新页面，否则会导致添加不成功",
            movingToGroupSuccessfully: "成功添加到组",
            maxDisplayItems: "最多添加{0}项",
            editRandomExtraction: "编辑随机抽取项",
            pleaseSelectACategory: "请选择一个分类",
            selectQuestionsCount: "当前选择共包含{0}题",
            selectQuestionsAndTotalPoints: "将随机抽取{0}题共{1}分",
            randomQuestionsSelectedTips: "总题数<b>{0}</b>题",
            sectionTotalPoints: "共<b>{0}</b>分",
            sectionLimitTime: "总用时<b>{0}</b>分钟",
            keepOnePartAtLeast: "至少保留一个部分",
            noSearchResult: "无搜索结果",
            noQuestionAndReselect: "当前选择没有试题，请重新选择。",
            sectionQuestionLimited: "每题限制时间<b>{0}</b>秒",
            examInfoTotalTime: "总时长：<span>{0}</span>分钟 &nbsp; <a href='javascript:;' class='edit-exam-time'>修改试卷时间<i class='fa fa-pencil' aria-hidden='true'></i></a>",
            examInfoTotalPoints: "总分值：<span>{0}</span>分",
            examInfoTotalQuestions: "总试题：<span>{0}</span>题",
            examInfoTotalSections: "共有部分：<span>{0}</span>",
            examTimeLimit: "试卷总时长设置",
            limitTheTotalLengthOfExam: "限制试卷总时长",
            additionalIntroduction: "附加题，该题可做可不做，答对加分，答错不扣分，附加题不影响试卷总分",
            whetherToDeleteRandomExtractions: "是否删除随机抽取项",
            whetherToDeleteSection: "删除该部分后，该部分的试题将会从试卷中移除。",
            deletePart: "删除部分",
            checkedQuestions: "已勾选 {0} 题",
            sectionTitle: "部分的标题",
            collapse: "收起",
            expand: "展开",
            noQuestionTips: "点击<span style='color:#36aafd'>“添加试题“</span>,可题库随机选题、手工选题、直接编辑试题、Word/Excel文档一键导入，每个人考试的试题一样！",
            noRandomQuestionTips: "<div class='random-no-question-tips-one'>暂无试题</div><div class='random-no-question-tips-two'>请点击 “添加分类” 按钮添加</div>",
            savePreAndRandomFailTips: "当前试卷模式为“固定+随机”，随机部分没有分类信息，请选择要从哪个分类中抽取试题数据",
            yourChangesMayNotBeSaved: "系统可能不会保存您所做的更改",
            examInfoEachQuetionTime: "每题限制：<span>{0}</span>秒 &nbsp; <a href='javascript:;' class='edit-exam-time'>修改试卷时间<i class='fa fa-pencil' aria-hidden='true'></i></a>",
            examTimeToQuestionTimeTips: "设置试卷时间后，部分的时间将不可用，是否继续设置试卷时间？",
            questionTimeToExamTimeTips: "设置部分时间后，试卷时间将不可用，是否继续设置部分时间？",
            sectionTimeMustLarge: "部分时间必须大于0",
            preAndRandomModeIsDifferent: "当前试卷出题方式为固定+随机，固定和随机必须同为标准模式，或者同为部分模式。",
            search: "搜索",
            switchTips: "系统不会保留您所作的修改，请先保存后切换。",
            switch: "切换",
            changeModeTips: "如需切换为旧版本，请将试卷模式切换为标准模式后再进行旧版本的切换。",
            dragTips: "拖动可以改变试题显示顺序",
            changeExamModeTips: "您确定要修改组卷模式吗？切换后原有的试题将会无效",

            rewardCountMoreThanQuestionCount: "奖励数量不可以大于关卡数，请重新修改",
            notCanSetLevel: "该闯关已有人参与，不允许再修改关卡",
            delAdvanceCashTip: "<p>《{0}》<label class='del-cash'>剩余余额：{1}元</label></p>",
            delAdvanceAmountTip: "<p class='del-amount'>总计：{0}元</p>",
            delAdvanceTip:"<p>您删除的试卷包含了红包余额，将返回到您的余额中</p>",
            deleteRegistersConfirm:"您确定要删除选择的{0}个报名模板吗？",
            movingToGroup: "正移动到补考组...",
            movingToGroupTips: "正移动到补考组，请勿刷新页面，否则会导致添加不成功",
            movingToGroupSuccessfully: "成功添加到组",
            maxDisplayItems: "最多添加{0}项",
            purchaseSpaceTitle: "购买空间",
            changePasswordTitle: "修改密码",
            uploadHeadImgTitle: "上传头像",
            systemHint: "系统提示",
            vertificationCodeIsIncorrect: "验证码不正确",
            randomQuestionTitle: "试题乱序设置",
            sureToDeleteNQuestions: "您确定要删除已勾选的 {0} 道试题吗？",
            exportRegstuSuccess: "<span class='success'>考生列表导出成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportRegstuFailed: "导出奖励列表失败，请联系我们客服QQ: 3322628959",
            previewRegister: "预览",
            uploadBackgroundTip: "请上传小于2M的png,jpg格式图片",
            needInputFull: "请填写完整的注册信息",
            registerFail: "报名失败",
            nameAndPhoneCanNotNull: "考生姓名和电话不能为空",
            nameAndEmailCanNotNull: "考生姓名和邮箱不能为空",
            enterExaminerSuccessfully: "录入成功!",
            emailFormatEeor: "您输入的邮箱格式不正确，请重新输入",
            emailForNull: "邮箱账号为空。",
            importSuccessfulNumberTips: "考生姓名和电话不能为空",
            recharge: "充值",
            smsTemplateTips: "【优考试】{0}邀请您参与{1}考试，链接<a target='_blank' href='https://ks.youkaoshi.cn/{2}'>ks.youkaoshi.cn/{2}</a>",
            send: "发送",
            selectAndUpload: "选择文件并上传",
            randomRedLowestTips:"单个红包奖励不能低于0.3元，总金额不能低于{0}元",
            exportExamRewardsSuccess: "<span class='success'>红包领取记录导出成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportExamRewardsFailed: "导出红包领取记录失败，请联系我们客服QQ: 3322628959",
            rewardCountIsNull: "请输入正确的红包个数",
            rewardRedAmountTips: "请输入正确的红包总金额",
            rewardRedProTips: "请输入正确的中奖概率",
            smsAmountsTwo: "￥{0}元",
            exportExamRewardsFailed: "导出红包领取记录失败，请联系我们客服QQ: 3322628959",
            amount: "￥{0}",
            priceAmounts: "￥{0}",
            subadminPrice: "{0}元/个/年",
            preAndRandomExportTips: "当前试卷类型是固定+随机，只能导出固定部分的考生答案！",
            continueExport: "继续导出",
            priceAmounts: "{0}",
            exportExamRewardsFailed: "导出红包领取记录失败，请联系我们客服QQ: 3322628959",
            exportExamRewardsMaxFailed: "单个红包奖励不能高于200元",
            exportCollectSuccess: "<span class='success'>问卷收集记录导出成功</span><br/><br/><span class='exam-title'>《{1}》</span><br/> <span class='download-tips'>2秒后浏览器将自动下载导出文件， 如果没有， 请</span><a href='{0}'>点击这里下载</a>",
            exportCollectFailed: "导出问卷收集记录失败，请联系我们客服QQ: 3322628959",
            anyCate:"所有分类",
            examQuestionsOrderByType: "按题型排序",
            someSectionDoNotHaveQuestion: "检测到某些部分不包含试题，请添加试题后保存。",
            anyCate: "所有分类",
            takenHaveNQuestions: "共有{0}题",
            jump: "跳转",
            specifiedGroupCanUseFaceRecognition: "<span style='color:#fd3636'>(需要设置账号登录考试才能使用)</span>",
            faceRecognitionLeftTips: "<span style='color:#999'>(人脸识别成功进入考试算1次)</span>",
            draftTips: "试卷处于草稿状态下，考生无法访问，请在完全设置好试卷各项参数后发布试卷。",
            saveExamTips: "试卷处于发布状态下，保存后将设置为草稿状态，试卷处于草稿状态下，考生无法访问，是否继续保存。",
            isReleaseTheExam: "当前试卷已存为草稿，确认考试时间等参数设置无误后即可发布。<br>注：若开启考后抽红包功能，务必仔细检查该设置。",
            release: "发布",
            addQuestions: "添加试题",
            releaseNow: "立即发布",
            releaseLater: "暂不发布",
            noQuestionToselectTipTwo: "您当前没有任何试题，请先<a href='{0}'>导入</a>或<a href='{1}'>添加</a>一些试题",
            getGroupStudentInformationTip: "您已设置账号登录考试，建议您无需再收集考生信息，请跳过该项。",
            getStudentInformationTip: "您可以通过下面的设置，设置您需要考生在考试时输入的信息，例如要求考生输入姓名，电话，身份证号码等。",
            atLeastAddOneChildQuestion: "至少添加一道子试题",
            questionsAnswerCouldNotBeEmpty: "答案不能为空，请填写答案",
            exportExcelTips: "你当前选择导出全部记录共<strong>{0}</strong>条,确定要全部导出吗？",
            exportPDFTips: "您当前已勾选全部记录共<strong>{0}</strong>条， 导出PDF较为复杂，可能需要较长时间才能导出完毕，请耐心等待。建议每次分批导出少于<strong>{1}</strong>条 ",
            changeIcon: "修改图标",
            notChangeIcon: "系统默认分类不允许修改图标",
            anyCate:"所有分类",
            selectUpToFiveGroups:"最多选择5个组",
            expandAll:"一键展开",
            collapseAll:"一键收起",
            pleaseSelectFiles: "请选择需要下载的附件",
            inputMaxLengthTips: "最多只能输入{0}个字符，汉字占两个字符",
            contact: "联系客服升级会员",
            exportTips: "你当前选择全部记录共{0}条，免费会员单次只能导{1}条，请分批导出！",
            exportAnswerTips: "“导出考生答案列表到EXCEL”功能仅限企业会员使用，其它会员不支持该功能！",
            exportReportPdfTips: "“导出考生报告(PDF)”功能仅限标准会员或以上会员使用，免费会员不支持该功能！",
            exportAnswersPdfTips: "“导出考生答卷(PDF)”功能仅限标准会员或以上会员使用，免费会员不支持该功能！",
            exportAllDetailTips: "“导出所有参考情况”功能仅限企业会员使用，其它会员不支持该功能！",
            selectedGroup: "已选<span styple='color:red;font-weight:bold'>{0}</span>组",
            cancelCollection: "收起",
            definiteCollection: "展开",
            selectedGroups: "（已选{}个考生组）",
            selectedGroupJs: "(已选<strong style='color:red'>{0}</strong>个考生组)",
            openIntegralTips: "必须设置账号登录考试才能开启积分功能",
            bestRankTips: "只显示最高分记录",
            bestRankOpenTips: "必须是指定组考试或强制微信考试才有最高分记录",
            pleaseInputKeywords: "请输入关键词搜索试卷",
            noSubCategory: "没有子分类",
            atLeastSelectOne: "请至少选择一项进行操作",
            inputCategoryName: "请输入分类名称",
            inputCategoryName: "请输入分类名称",
            collapsTips: "收起",
            expandTips: "展开",
            existFieldTips: "已存在与{0}相似的字段，确定要添加吗？",
            selectGroupOrStudent: "请选择指定组或指定考生",
            rewardTimesTips: "请输入正确的中奖次数",
	}
    window.OELang = lang;
})(window);

